### PR TITLE
Test all jobs on PHP 8.1

### PR DESCRIPTION
**Pull request by ruudk**

### CODE REVIEW

**Comment by ruudk** [comment]
@ondrejmirtes How to solve this? I think the problem is that the lowest PHPStan on PHP 8.1 does not contain the compatible Symfony components. Should we bump the minimum required PHPStan version?

**Comment by ondrejmirtes** [comment]
@ruudk We can dynamically update PHPStan to ^1.0 when the CI is running on PHP 8.1. I don't want to change the mininum version in composer.json for everyone.

**Comment by ruudk** [comment]
@ondrejmirtes Updated. It appeared that we already used that for PHP 8.0 :)

**Comment by ruudk** [comment]
@ondrejmirtes can this be merged?

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
