### PR TITLE
Enhancement: Switch to using GitHub actions

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] switches to using GitHub actions

💁‍♂ Perhaps this is something that could be interesting for the other repositories in the @phpstan organization as well?

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Hi, I’ve started heavily investing into automation by Travis CI in the phpstan/phpstan and phpstan/phpstan-src repositories. Look there to see what I’ve been doing.

I’m not familiar with GitHub actions and I’m not sure about the benefits. If they’d make my job easier for the tasks I need I’d consider the switch but the benefits would have to be huge and clear to invest time learning a new tool.

**Comment by localheinz** [comment]
@ondrejmirtes 

I know, and I think the level of automation you have built up there is very, very nice!

Personally, I have switched all of my repositories away from Travis CI to GitHub actions. They have quite a lot of advantages. I'm sure it would be possible to switch all of the work that is currently done on Travis using GitHub actions as well.

Perhaps put this on hold until later?

What do you think, maybe start with `phpstan/phpstan-src` and `phpstan/phpstan`? If the automation can be mimicked using GitHub actions *and* is better at the same time, perhaps then it would make sense to switch to GitHub actions for all other repositories?

**Comment by ondrejmirtes** [comment]
Yeah, I don’t think this is the right time to start rewriting something now that it started working for me 😊 I’d have many questions how to manage it, how to manage secret keys etc...

(But it would be interesting to build an action that presents PHPStan findings directly in the GitHub UI as a status check.)

**Comment by localheinz** [comment]
@ondrejmirtes 

No problem!

In regard to secrets, they can be provided via https://github.com/phpstan/extension-installer/settings/secrets - here's an example:

Screen Shot 2019-12-16 at 15 59 04

A `GITHUB_TOKEN` for use with the current repository is automatically provided.

**Comment by ondrejmirtes** [comment]
I switched myself :) Thank you.

**Pull request closed without merging**
