### PR TITLE
Enhancement: Sort packages by name

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] sorts packages by name before rendering information in terminal

### CODE REVIEW

**Comment by localheinz** [comment]
@ondrejmirtes 

Adjusted!

**Comment by ondrejmirtes** [comment]
This actually does a different thing than the previous version. `$notInstalledPackages` and `$installedPackages` will be output non-alphabetically. We need three `ksort()` calls :)

**Comment by localheinz** [comment]
@localheinz 

Sorry, I should have taken a closer look.

**Comment by ondrejmirtes** [comment]
Thank you :)

**Comment by localheinz** [comment]
Thank you, @ondrejmirtes!

**Pull request merged**
